In [1]:
import napari
import numpy as np
from napari.types import LabelsData
from magicgui.widgets import FunctionGui

def my_function(label_image):
    global label_image2
    print(label_image.name, label_image.data)
    print("Did I get the \"opening\" layer? ", np.array_equal(label_image.data,label_image2))

class MyGui(FunctionGui):
    def __init__(self,param_options):
        super().__init__(
          my_function,
          call_button=False,
          layout='vertical',
          auto_call=True,
          param_options=param_options
        )
        print("Started")
        # do whatever other initialization you want here

# Create layers
image = np.random.rand(64, 64)*255
viewer = napari.view_image(image, name="My Image")
from skimage.filters import threshold_otsu
from skimage.morphology import binary_opening
# add label layers
thresh = threshold_otsu(image)
label_image1 = image>thresh
label_image2 = binary_opening(label_image1)
labels_layer1 = viewer.add_labels(label_image1, name='otsu')
labels_layer2 = viewer.add_labels(label_image2, name='opening')

layers_list = [labels_layer2]

widget1 = MyGui(param_options={'label_image' : {'choices' : layers_list}})

print(widget1._param_options)

layers_list = [labels_layer1, labels_layer2]

# widget1.label_image.choices = layers_list
print(widget1._param_options)
widget1.__init__({'label_image' : {'choices' : layers_list}})

viewer.window.add_dock_widget(widget1)

C:\Users\ryans\anaconda3\envs\np_workflows_v1\lib\site-packages\napari_tools_menu\__init__.py:165: FutureWarning: Public access to Window.qt_viewer is deprecated and will be removed in
v0.5.0. It is considered an "implementation detail" of the napari
application, not part of the napari viewer model. If your use case
requires access to qt_viewer, please open an issue to discuss.
  self.tools_menu = ToolsMenu(self, self.qt_viewer.viewer)


Started
{'label_image': {'choices': [<Labels layer 'opening' at 0x1a59450c490>]}}
{'label_image': {'choices': [<Labels layer 'opening' at 0x1a59450c490>]}}
Started


opening [[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Did I get the "opening" layer?  True
opening [[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Did I get the "opening" layer?  True
otsu [[1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 1]
 ...
 [1 0 1 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
Did I get the "opening" layer?  False
otsu [[1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 1]
 ...
 [1 0 1 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
Did I get the "opening" layer?  False
